export { AboutSection } from './about-section';
export { CTASection } from './cta-section';
export { FeaturesSection } from './features-section';
export { HowItWorksSection } from './how-it-works-section';
export { LandingFooter } from './footer';
export { LandingHeader } from './header';
export { HeroSection } from './hero-section';
export { TopProductsSection } from './top-products-section';
export { TrackingSection } from './tracking-section';
